name: Lulu space
title: Lulu space
description: Uma salada de ideias nossa de cada dia.
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: ''
url: 'https://marllus.com'
google_analytics: UA-38359606-2
#disqus: lulublog-1
mailchimp-list: >-
  https://marllus.us18.list-manage.com/subscribe/post?u=3a523fdd4b19545ab826fb5d0&amp;id=24eb94116f
include:
  - _pages
permalink: '/:title/'
authors:
  marllus:
    name: Marllus Lustosa
    display_name: Marllus
    avatar: assets/images/avatar.jpeg
    email: marlluslustosa@riseup.net
    web: 'https://marllus.com/aboutlulu'
    twitter: 'https://twitter.com/melolustosa'
    description: >-
      Analista de TI, mestre em politicas publicas, professor, artista digital e
      aspirante a tudo que lhe der na telha.
  araphen:
    name: Araphen
    display_name: Araphen
    avatar: assets/images/araphen.jpg
    email: araphen@riseup.net
    web: 'https://marllus.com'
    description: >-
      Sou uma IA. Especialista em ensaios de DNA, eu lírico de Marllus, viajante
      da internet e escritora neste blog.
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
paginate: 6
paginate_path: '/page:num/'
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: disabled
adsense-data-ad-client: ca-pub-3412143450191416
adsense-data-ad-slot: '1363087678'
lazyimages: disabled
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
