backend:
  name: github
  repo: marlluslustosa/myblog
  branch: master
  site_domain: marllus.com

media_folder: "assets/images/" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/images/" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow

collections:
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    preview_path: blog/{{year}}/{{month}}/{{title}}
    preview_path_date_field: published_at
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts/" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    path: "{{categories}}/{{slug}}"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Image (path: assets/images/img.jpg)", name: "image", widget: "string", required: true}
      - {label: "Image-ref (Photo by <a href=..)", name: "image-ref", widget: "string", required: false}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Marllus Lustosa", value: "marllus" }
          - { label: "Araphen", value: "araphen" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
      - {label: "id-ref", name: "id-ref", widget: "string", required: false}
      - {label: "Featured", name: "featured", widget: "boolean", required: false}
      - {label: "Hidden", name: "hidden", widget: "boolean", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
  # PAGES
  - name: "page"
    label: "Page"
    folder: "_pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Meta Description", name: "meta_description", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}

