name: OWASP scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.4.0 
        with:
          target: 'http://www.ufc.br'
