name: OWASP scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#caso coloque agendado
#on:
#  schedule:
    # Runs every day At 01:00.
#    - cron:  '0 1 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.4.0 
        with:
          target: 'https://marllus.com'
